INSERT INTO candidates (contact_number, date_of_birth, email, full_name) values ('+381621127650', '1998-04-25 00:00:00.000000', 'radovic.milorad1998@gmail.com', 'Milorad Radovic');
INSERT INTO candidates (contact_number, date_of_birth, email, full_name) values ('+381621127651', '1992-05-26 00:00:00.000000', 'pera.peric@gmail.com', 'Pera Peric');
INSERT INTO candidates (contact_number, date_of_birth, email, full_name) values ('+381621127652', '2000-03-15 00:00:00.000000', 'nikola.nikolic@gmail.com', 'Nikola Nikolic');
INSERT INTO candidates (contact_number, date_of_birth, email, full_name) values ('+381621127653', '1993-04-03 00:00:00.000000', 'marko.markovic@gmail.com', 'Marko Markovic');
INSERT INTO candidates (contact_number, date_of_birth, email, full_name) values ('+381621127654', '1994-12-11 00:00:00.000000', 'petar.petrovic@gmail.com', 'Petar Petrovic');
INSERT INTO candidates (contact_number, date_of_birth, email, full_name) values ('+381621127655', '1995-11-12 00:00:00.000000', 'stefan.stefanovic@gmail.com', 'Stefan Stefanovic');
INSERT INTO candidates (contact_number, date_of_birth, email, full_name) values ('+381621127656', '1996-10-25 00:00:00.000000', 'marija.markovic@gmail.com', 'Marija Markovic');
INSERT INTO candidates (contact_number, date_of_birth, email, full_name) values ('+381621127657', '1997-09-13 00:00:00.000000', 'nikolina.nikolic@gmail.com', 'Nikolina Nikolic');
INSERT INTO candidates (contact_number, date_of_birth, email, full_name) values ('+381621127658', '1998-08-17 00:00:00.000000', 'nina.visnjic@gmail.com', 'Nina Visnjic');
INSERT INTO candidates (contact_number, date_of_birth, email, full_name) values ('+381621127659', '1999-07-01 00:00:00.000000', 'milica.milic@gmail.com', 'Milica Milic');


INSERT INTO skills (name) values ('Java programming');
INSERT INTO skills (name) values ('C# programming');
INSERT INTO skills (name) values ('C programming');
INSERT INTO skills (name) values ('Python programming');
INSERT INTO skills (name) values ('Databases');
INSERT INTO skills (name) values ('Matlab');
INSERT INTO skills (name) values ('Angular');
INSERT INTO skills (name) values ('Spring Boot');
INSERT INTO skills (name) values ('React');
INSERT INTO skills (name) values ('Django');
INSERT INTO skills (name) values ('JQuery');
INSERT INTO skills (name) values ('C++ programming');
INSERT INTO skills (name) values ('JavaScript');
INSERT INTO skills (name) values ('WordPress');
INSERT INTO skills (name) values ('SQL');
INSERT INTO skills (name) values ('Android programming');
INSERT INTO skills (name) values ('Vue.js');
INSERT INTO skills (name) values ('Web design');
INSERT INTO skills (name) values ('English language');
INSERT INTO skills (name) values ('Italian language');


INSERT INTO candidate_skill (candidate_id, skill_id) values (1, 2);
INSERT INTO candidate_skill (candidate_id, skill_id) values (1, 15);
INSERT INTO candidate_skill (candidate_id, skill_id) values (1, 17);
INSERT INTO candidate_skill (candidate_id, skill_id) values (1, 7);
INSERT INTO candidate_skill (candidate_id, skill_id) values (1, 1);
INSERT INTO candidate_skill (candidate_id, skill_id) values (2, 13);
INSERT INTO candidate_skill (candidate_id, skill_id) values (2, 14);
INSERT INTO candidate_skill (candidate_id, skill_id) values (2, 10);
INSERT INTO candidate_skill (candidate_id, skill_id) values (2, 20);
INSERT INTO candidate_skill (candidate_id, skill_id) values (2, 19);
INSERT INTO candidate_skill (candidate_id, skill_id) values (3, 3);
INSERT INTO candidate_skill (candidate_id, skill_id) values (3, 4);
INSERT INTO candidate_skill (candidate_id, skill_id) values (3, 5);
INSERT INTO candidate_skill (candidate_id, skill_id) values (3, 6);
INSERT INTO candidate_skill (candidate_id, skill_id) values (3, 7);
INSERT INTO candidate_skill (candidate_id, skill_id) values (4, 8);
INSERT INTO candidate_skill (candidate_id, skill_id) values (4, 12);
INSERT INTO candidate_skill (candidate_id, skill_id) values (4, 11);
INSERT INTO candidate_skill (candidate_id, skill_id) values (4, 10);
INSERT INTO candidate_skill (candidate_id, skill_id) values (4, 16);
INSERT INTO candidate_skill (candidate_id, skill_id) values (5, 5);
INSERT INTO candidate_skill (candidate_id, skill_id) values (5, 14);
INSERT INTO candidate_skill (candidate_id, skill_id) values (5, 15);
INSERT INTO candidate_skill (candidate_id, skill_id) values (5, 16);
INSERT INTO candidate_skill (candidate_id, skill_id) values (5, 20);
INSERT INTO candidate_skill (candidate_id, skill_id) values (6, 1);
INSERT INTO candidate_skill (candidate_id, skill_id) values (6, 2);
INSERT INTO candidate_skill (candidate_id, skill_id) values (6, 3);
INSERT INTO candidate_skill (candidate_id, skill_id) values (6, 4);
INSERT INTO candidate_skill (candidate_id, skill_id) values (6, 5);
INSERT INTO candidate_skill (candidate_id, skill_id) values (7, 17);
INSERT INTO candidate_skill (candidate_id, skill_id) values (7, 18);
INSERT INTO candidate_skill (candidate_id, skill_id) values (7, 13);
INSERT INTO candidate_skill (candidate_id, skill_id) values (7, 10);
INSERT INTO candidate_skill (candidate_id, skill_id) values (7, 1);
INSERT INTO candidate_skill (candidate_id, skill_id) values (8, 8);
INSERT INTO candidate_skill (candidate_id, skill_id) values (8, 18);
INSERT INTO candidate_skill (candidate_id, skill_id) values (8, 20);
INSERT INTO candidate_skill (candidate_id, skill_id) values (8, 3);
INSERT INTO candidate_skill (candidate_id, skill_id) values (8, 4);
INSERT INTO candidate_skill (candidate_id, skill_id) values (9, 5);
INSERT INTO candidate_skill (candidate_id, skill_id) values (9, 9);
INSERT INTO candidate_skill (candidate_id, skill_id) values (9, 13);
INSERT INTO candidate_skill (candidate_id, skill_id) values (9, 17);
INSERT INTO candidate_skill (candidate_id, skill_id) values (9, 20);
INSERT INTO candidate_skill (candidate_id, skill_id) values (10, 10);
INSERT INTO candidate_skill (candidate_id, skill_id) values (10, 1);
INSERT INTO candidate_skill (candidate_id, skill_id) values (10, 11);
INSERT INTO candidate_skill (candidate_id, skill_id) values (10, 15);
INSERT INTO candidate_skill (candidate_id, skill_id) values (10, 18);
