INSERT INTO skills (name) values ('Java programming');
INSERT INTO skills (name) values ('C# programming');
INSERT INTO skills (name) values ('C programming');
INSERT INTO skills (name) values ('Python programming');
INSERT INTO skills (name) values ('Databases');
INSERT INTO skills (name) values ('Matlab');
INSERT INTO skills (name) values ('Angular');
INSERT INTO skills (name) values ('Spring Boot');
INSERT INTO skills (name) values ('React');
INSERT INTO skills (name) values ('Django');
INSERT INTO skills (name) values ('JQuery');
INSERT INTO skills (name) values ('C++ programming');
INSERT INTO skills (name) values ('JavaScript');
INSERT INTO skills (name) values ('WordPress');
INSERT INTO skills (name) values ('SQL');
INSERT INTO skills (name) values ('Android programming');
INSERT INTO skills (name) values ('Vue.js');
INSERT INTO skills (name) values ('Web design');
INSERT INTO skills (name) values ('English language');
INSERT INTO skills (name) values ('Italian language');
